# Generated by Django 5.2.11 on 2026-02-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml_file', models.FileField(upload_to='imports/%Y/%m/%d/', verbose_name='YAML файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров')),
                ('categories_count', models.PositiveIntegerField(default=0, verbose_name='Количество категорий')),
                ('parameters_count', models.PositiveIntegerField(default=0, verbose_name='Количество параметров')),
            ],
            options={
                'verbose_name': 'Импорт товаров',
                'verbose_name_plural': 'Импорт товаров',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
