# Generated by Django 5.2.11 on 2026-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_importtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='price_rrc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рекомендуемая розничная цена'),
        ),
    ]
