# Generated by Django 5.2.11 on 2026-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_productinfo_price_rrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
